FROM rust:latest

WORKDIR /app

# Install dependencies
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy the source code
COPY . .

# Set default command to run tests
CMD ["cargo", "test", "--", "--nocapture"]
