//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::AmbulanceCarDetailsMakeEnum;
use super::sea_orm_active_enums::AmbulanceCarDetailsModelEnum;
use super::sea_orm_active_enums::AmbulanceStatusEnum;
use super::sea_orm_active_enums::AmbulanceTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)] // Add Serialize and Deserialize here
#[sea_orm(table_name = "ambulance")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hospital_id: Uuid,
    pub ambulance_ic: i32,
    pub vehicle_number: String,
    pub make: Option<String>,
    pub year: Option<i32>,
    pub capacity: Option<i32>,
    pub mission: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub passengers: Option<Json>,
    pub driver_name: Option<String>,
    pub driver_license: Option<String>,
    pub last_service_date: Option<DateTime>,
    pub next_service_date: Option<DateTime>,
    pub mileage: Option<i32>,
    pub fuel_type: Option<String>,
    pub registration_number: Option<String>,
    pub insurance_provider: Option<String>,
    pub insurance_expiry_date: Option<DateTime>,
    pub notes: Option<String>,
    pub car_details_year: i32,
    pub car_details_color: String,
    pub car_details_is_ambulance: bool,
    pub car_details_license_plate: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub car_details_mileage: Option<f64>,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub location_latitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub location_longitude: Decimal,
    pub r#type: AmbulanceTypeEnum,
    pub status: AmbulanceStatusEnum,
    pub car_details_make: AmbulanceCarDetailsMakeEnum,
    pub car_details_model: AmbulanceCarDetailsModelEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_many = "super::emergency::Entity",
        from = "Column::Id",
        to = "super::emergency::Column::AmbulanceId"
    )]
    Emergency,
}

impl Related<super::emergency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Emergency.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
// Payload structure for creating or updating an ambulance entity
// This structure is used to deserialize JSON data into a Rust struct
// It can also be used to serialize the struct back into JSON
// when returning responses from an API endpoint
pub struct AmbulancePayload {
    pub ambulance_ic: Option<i32>,
    #[serde(rename = "vehicleNumber")]
    pub vehicle_number: Option<String>,
    pub make: Option<String>,
    pub year: Option<i32>,
    pub capacity: Option<i32>,
    pub mission: Option<String>,
    pub passengers: Option<Json>,
    pub driver_name: Option<String>,
    pub driver_license: Option<String>,
    #[serde(rename = "hospitalName")]
    pub hospital_name: Option<String>,
    pub last_service_date: Option<DateTime>,
    pub next_service_date: Option<DateTime>,
    pub mileage: Option<i32>,
    #[serde(rename = "fuelType")]
    pub fuel_type: Option<String>,
    pub registration_number: Option<String>,
    pub insurance_provider: Option<String>,
    pub insurance_expiry_date: Option<DateTime>,
    pub notes: Option<String>,
    pub location_longitude: Option<Decimal>,
    pub location_latitude: Option<Decimal>,
    pub r#type: Option<AmbulanceTypeEnum>,
    pub status: Option<AmbulanceStatusEnum>,
    #[serde(rename = "carDetails")]
    pub car_details: Option<CarDetails>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CarDetails {
    pub year: Option<i32>,
    pub color: Option<String>,
    pub is_ambulance: Option<bool>,
    pub license_plate: Option<String>,
    pub mileage: Option<f64>,
    pub make: Option<AmbulanceCarDetailsMakeEnum>,
    pub model: Option<AmbulanceCarDetailsModelEnum>,
}
pub enum AmbulanceId {
    Uuid(Uuid),
    Integer(i32),
}

// DTO (Data Transfer Object) for the frontend
#[derive(Debug, Serialize)]
pub struct StatusDto {
    pub value: String,
    pub label: String,
}
