//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::CardSizeEnum;
use super::sea_orm_active_enums::CardTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "card")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub content: String,
    #[sea_orm(unique)]
    pub card_ic: i32,
    pub icon: Option<String>,
    pub position: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub data_config: Option<Json>,
    pub dashboard_id: Option<Uuid>,
    pub card_type: Option<CardTypeEnum>,
    pub size: Option<CardSizeEnum>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dashboard::Entity",
        from = "(Column::DashboardId, Column::DashboardId)",
        to = "(super::dashboard::Column::Id, super::dashboard::Column::Id)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dashboard,
}

impl Related<super::dashboard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dashboard.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CardPayload {
    pub title: Option<String>,
    pub content: Option<String>,
    pub icon: Option<String>,
    pub position: Option<i32>,
    pub data_config: Option<Json>,
    pub dashboard_id: Option<Uuid>,
    pub card_type: Option<CardTypeEnum>,
    pub size: Option<CardSizeEnum>,
}
