//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11
use super::sea_orm_active_enums::EmergencyIncidentEnum;
use super::sea_orm_active_enums::EmergencySeverityEnum;
use super::sea_orm_active_enums::EmergencyStatusEnum;
use crate::entity::patient::PatientRequestBody;
use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "emergency")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: Uuid,
    pub hospital_id: Option<Uuid>, // This will now correctly map to UUID NULL
    pub ambulance_id: Option<Uuid>,
    pub emergency_ic: String,
    pub reported_by: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)] // This is correct for Option<String> to TEXT
    pub notes: Option<String>,
    pub resolved_at: Option<NaiveDateTime>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub modification_attempts: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub emergency_latitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub emergency_longitude: Decimal,
    pub status: EmergencyStatusEnum,
    pub severity: EmergencySeverityEnum,
    pub incident_type: EmergencyIncidentEnum,
    pub description: Option<String>,
}
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ambulance::Entity",
        from = "(Column::AmbulanceId, Column::AmbulanceId)",
        to = "(super::ambulance::Column::Id, super::ambulance::Column::Id)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ambulance,
    // Emergency has many EmergencyPatient (join table)
    #[sea_orm(
        has_many = "super::emergency_patient::Entity",
        from = "Column::Id",
        to = "super::emergency_patient::Column::EmergencyId"
    )]
    EmergencyPatient,
}

impl Related<super::ambulance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ambulance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct EmergencyRequestBody {
    pub notes: Option<String>,
    #[serde(rename = "emergencyLatitude")]
    pub emergency_latitude: Decimal,
    #[serde(rename = "emergencyLongitude")]
    pub emergency_longitude: Decimal,
    #[serde(rename = "incidentType")]
    pub incident_type: EmergencyIncidentEnum,
    pub description: Option<String>,
    pub patients: Option<Vec<PatientRequestBody>>,
}
