//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod admission;
pub mod ambulance;
pub mod amenities;
pub mod appointment;
pub mod bed;
pub mod bill;
pub mod card;
pub mod customers;
pub mod dashboard;
pub mod department;
pub mod emergency;
pub mod emergency_patient;
pub mod guard;
pub mod hospital;
pub mod inventory;
pub mod medical_record;
pub mod patient;
pub mod patient_doctor;
pub mod patient_info;
pub mod person;
pub mod prescription;
pub mod prescription_order;
pub mod room;
pub mod sea_orm_active_enums;
pub mod staff;
pub mod staff_schedule;
pub mod supplier;
pub mod treatment;
pub mod user_profile;
pub mod auth_identity;
