//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::RoomTypeEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "room")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hospital_id: i32,
    pub room_number: Option<String>,
    pub rate_per_day: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub floor: Option<i32>,
    pub view: Option<String>,
    pub r#type: RoomTypeEnum,
    pub room_ic: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
