//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::{GenderEnum, StaffRoleEnum};
use crate::entity::person;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid, // PK and FK to person
    pub hospital_id: Uuid,
    pub department_id: Uuid,
    pub specialization: Option<String>,
    pub role: StaffRoleEnum,
    pub staff_ic: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "person::Entity",
        from = "Column::Id",
        to = "person::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Person,
}
impl Related<person::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Person.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Default, Debug, Serialize, Deserialize, Clone)]
pub struct StaffRequestBody {
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub hospital_name: Option<String>,
    pub date_of_birth: Option<Date>,
    pub gender: Option<GenderEnum>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub address: Option<String>,
    pub department_name: Option<String>,
    pub specialization: Option<String>,
    pub role: Option<StaffRoleEnum>,
}
#[derive(Serialize, Deserialize)]
pub struct StaffWithPerson {
    pub staff: Model,
    pub person: person::Model,
}
